name: easy
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 4.0.0+21

environment:
    sdk: ">=3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_svg: ^2.0.5
    flutter_bloc: ^8.1.3
    package_info_plus: ^8.0.2
    device_info_plus: ^10.1.2
    ios_utsname_ext: ^2.3.0
    cupertino_icons: ^1.0.2
    go_router: ^14.2.3
    flutter_dotenv: ^5.1.0
    get_it: ^7.7.0
    hive_flutter: ^1.1.0
    http: ^1.2.2
    internet_connection_checker_plus: ^2.5.1
    gap: ^3.0.1
    fca: ^0.0.10
    fpdart: ^1.1.0
    device_uuid: ^0.0.4
    local_auth: ^2.3.0
    encrypt: ^5.0.3
    geolocator: ^13.0.1
    turf: ^0.0.10
    geocoding: ^3.0.0
    camera: ^0.11.0+2
    path_provider: ^2.1.4
    month_picker_dialog: ^5.1.1
    intl: ^0.19.0
    flutter_html: ^3.0.0-beta.2
    image: ^4.2.0
    flutter_local_notifications: ^17.2.2
    timezone: ^0.9.4
    flutter_timezone: ^3.0.0
    firebase_core: ^2.24.2
    firebase_messaging: ^14.7.10
    permission_handler: ^11.3.1

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_launcher_icons: ^0.13.1

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    assets:
        - .env
        - assets/svgs/
        - assets/images/
        - shorebird.yaml
        - assets/audio/

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/icon.png"
