// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtlWl8fTZ8nw01N6PUfMy1Sj0ZZ4jLr28',
    appId: '1:305440063960:web:89313851ac256e9aebf2ad',
    messagingSenderId: '305440063960',
    projectId: 'taspen-easy',
    authDomain: 'taspen-easy.firebaseapp.com',
    storageBucket: 'taspen-easy.appspot.com',
    measurementId: 'G-G5NNB3YP7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ_gKje8yeXk2WDrjXErVL5yQkgFeYmdQ',
    appId: '1:305440063960:android:e128ab849695082cebf2ad',
    messagingSenderId: '305440063960',
    projectId: 'taspen-easy',
    storageBucket: 'taspen-easy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLSLYrjyNuLZrKSIPk-HtZBDW7-4WDuOs',
    appId: '1:305440063960:ios:e071fa4a2e84d2f5ebf2ad',
    messagingSenderId: '305440063960',
    projectId: 'taspen-easy',
    storageBucket: 'taspen-easy.appspot.com',
    iosBundleId: 'com.taspen.easy2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLSLYrjyNuLZrKSIPk-HtZBDW7-4WDuOs',
    appId: '1:305440063960:ios:c66a14456c78e17cebf2ad',
    messagingSenderId: '305440063960',
    projectId: 'taspen-easy',
    storageBucket: 'taspen-easy.appspot.com',
    iosBundleId: 'com.example.easy',
  );
}
